'use strict';

let Activity = require('../../../app/models/activity');

global.createActivity = () =>
  Activity.create({
    logId: new Date().getTime(),
    loaded: false,
    distance: 10.23,
  });

global.mockActivityData = () => (
  { declaration: { attributes: { version: '1.0', encoding: 'UTF-8', standalone: 'yes' } },
    root:
      { name: 'TrainingCenterDatabase',
        attributes: { xmlns: 'http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2' },
        children: [
          { name: 'Activities',
            attributes: {},
            children: [
              { name: 'Activity',
                attributes: { Sport: 'Running' },
                children: [
                  { name: 'Id', attributes: {}, children: [],
                    content: '2016-03-28T18:10:19.000+08:00' },
                  { name: 'Lap',
                    attributes: { StartTime: '2016-03-28T18:10:19.000+08:00' },
                    children: [
                      { name: 'TotalTimeSeconds', attributes: {}, children: [], content: '2057.0' },
                      { name: 'DistanceMeters', attributes: {}, children: [],
                        content: '10434.454680960709' },
                      { name: 'Calories', attributes: {}, children: [], content: '324' },
                      { name: 'Intensity', attributes: {}, children: [], content: 'Active' },
                      { name: 'TriggerMethod', attributes: {}, children: [], content: 'Manual' },
                      { name: 'Track', attributes: {},
                        children: [
                          { name: 'Trackpoint',
                            attributes: {},
                            children: [
                              { name: 'Time',
                                attributes: {},
                                children: [],
                                content: '2016-03-28T18:10:19.470+08:00' },
                              { name: 'Position',
                                attributes: {},
                                children: [
                                  { name: 'LatitudeDegrees',
                                    attributes: {},
                                    children: [],
                                    content: '1.2821564674377441' },
                                  { name: 'LongitudeDegrees',
                                    attributes: {},
                                    children: [],
                                    content: '103.85004651546478' },
                                ],
                                content: '' },
                              { name: 'AltitudeMeters',
                                attributes: {},
                                children: [],
                                content: '38.39' },
                              { name: 'DistanceMeters',
                                attributes: {},
                                children: [],
                                content: '0.0' },
                              { name: 'HeartRateBpm',
                                attributes: {},
                                children: [
                                  { name: 'Value', attributes: {}, children: [], content: '99' },
                                ],
                                content: '' },
                            ],
                            content: '' },
                          { name: 'Trackpoint',
                            attributes: {},
                            children: [
                              { name: 'Time',
                                attributes: {},
                                children: [],
                                content: '2016-03-28T18:10:24.000+08:00' },
                              { name: 'Position',
                                attributes: {},
                                children: [
                                  { name: 'LatitudeDegrees',
                                    attributes: {},
                                    children: [],
                                    content: '1.2821564674377441' },
                                  { name: 'LongitudeDegrees',
                                    attributes: {},
                                    children: [],
                                    content: '103.85004651546478' },
                                ],
                                content: '' },
                              { name: 'AltitudeMeters',
                                attributes: {},
                                children: [],
                                content: '38.39' },
                              { name: 'DistanceMeters',
                                attributes: {},
                                children: [],
                                content: '0.0' },
                              { name: 'HeartRateBpm',
                                attributes: {},
                                children: [
                                  { name: 'Value', attributes: {}, children: [], content: '97' },
                                ],
                                content: '' },
                            ],
                            content: '' },
                        ],
                        content: '' },
                    ],
                    content: '' },
                  { name: 'Creator',
                    attributes: {
                      'xsi:type': 'Device_t',
                      'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance',
                    },
                    children: [
                      { name: 'Name', attributes: {}, children: [], content: 'Fitbit iPhone App' },
                      { name: 'UnitId', attributes: {}, children: [], content: '0' },
                      { name: 'ProductID', attributes: {}, children: [], content: '0' },
                    ],
                    content: '' },
                ],
                content: '',
              },
            ],
            content: '' },
        ],
        content: '' },
  });
